# Imports
Here we import the necessary modules which will help us to 

In [ ]:
import pandas as pd
import numpy as np
from pyanp import priority
from pyanp import limitmatrix as lm

# Data
The data to get started needs to be loaded in as either a numpy array or via an excel spreadsheet, for sake of simplicity an excel spreadsheet will be used
- We need to load all our piecewise comparison matrices in from excel into python in order to get the weights (or priorities)
- When using excel as the input medium, each piecewise comparison matrix needs to be in a seperate excel file in order to assign it a variable, which can be slower but for the sake of understanding is far easier

In [ ]:
criteria_mat = priority.get_matrix("Critera_Matrix.xlsx")
AltTop = priority.get_matrix("AltwrtToppings.xlsx")
AltCrust = priority.get_matrix("AltwrtCrust.xlsx")
AltCheese = priority.get_matrix("AltwrtCheeseSauce.xlsx")
AltX = priority.get_matrix("AltwrtXFactor.xlsx")

# Getting weights/priorities
We now need to get the weights/priorities in order to further our process

## Priorities for criteria matrix

In [ ]:
priority.pri_eigen(criteria_mat)

## Priorities for Alternatives with respect to toppings

In [ ]:
priority.pri_eigen(AltTop)

## Priorities for Alternatives with respect to crust

In [ ]:
priority.pri_eigen(AltCrust)

## Priorities for Alternatives with respect to cheese to sauce ratio

In [ ]:
priority.pri_eigen(AltCheese)

## Priorities for Alternatives with respect to X-Factor

In [ ]:
priority.pri_eigen(AltX)

# Super Matrix
Now that we have gotten priorities for all relevant alternatives with respect to the criteria, we now need to construct a super matrix containing the goal, all criteria (c1 ... c4), and all alternatives (a1 ... a5), which results in a 10 x 10 matrix.

In order to finalize this matrix, we need to construct one last piecewise comparison matrix which ranks each restaurants with respect to each category, which is purely subjective and is described in the example section (size 4 x 5)

In [14]:
supermat = lm.get_matrix("SuperMatrix.xlsx")
print(supermat)

[[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.18 0.   0.   0.   0.   0.41 0.22 0.22 0.25 0.17]
 [0.51 0.   0.   0.   0.   0.18 0.26 0.23 0.3  0.26]
 [0.22 0.   0.   0.   0.   0.18 0.22 0.27 0.3  0.26]
 [0.09 0.   0.   0.   0.   0.22 0.3  0.27 0.15 0.31]
 [0.   0.42 0.08 0.11 0.39 0.   0.   0.   0.   0.  ]
 [0.   0.15 0.29 0.31 0.3  0.   0.   0.   0.   0.  ]
 [0.   0.26 0.46 0.12 0.07 0.   0.   0.   0.   0.  ]
 [0.   0.14 0.13 0.41 0.16 0.   0.   0.   0.   0.  ]
 [0.   0.03 0.04 0.05 0.08 0.   0.   0.   0.   0.  ]]


# Limit Matrix
From the super matrix, we can calculate the limit matrix by raising the super matrix to the power of K where K is an arbitarily large value, this will yield rankings for each pizza restaurant which we can read off to see which restaurant ranks supreme based on the given criteria 

In [22]:
lm.calculus(supermat)

Count was 0


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.27365816, 0.27365816, 0.27365816, 0.27365816,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.24216369, 0.24216369, 0.24216369, 0.24216369,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.24093964, 0.24093964, 0.24093964, 0.24093964,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.24323852, 0.24323852, 0.24323852, 0.24323852,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.2556759 , 0.        , 0.        , 0.        , 0.        ,
        0.2556759 , 0.2556759 , 0.2556759 , 0.2556759 , 0.2556759 ],
       [0.25893904, 0.        , 0.        , 0.        , 0.        ,
        0.25893904, 0.25893904, 0.25893904, 0.25893904, 0.25893904],
       [0.22848587, 0.        , 0.       

Now that we have obtained the limit matrix, we can extract column 1's 6-10th element which correspond to the ranking of each restaurant accordingly

In [26]:
lm.calculus(supermat)[: ,0]

Count was 0


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.2556759 , 0.25893904, 0.22848587, 0.20749684, 0.04940236])

# Ranking using ANP
- 1) Thirsty Scarecrow
- 2) Romans
- 3) Ginos
- 4) Bohemia
- 5) En-route